apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api-container
        image: simple-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
